pull_request_rules:
  - name: backport patches to v1.8.2+RAI
    conditions:
      - base=master
      - label=backport-v1.8.2+RAI
    actions:
      backport:
        branches:
          - v1.8.2+RAI
        assignees:
          - "{{ author }}"
        label_conflicts: backport-conflicts
  - name: backport patches to v1.9.2+RAI
    conditions:
      - base=master
      - label=backport-v1.9.2+RAI
    actions:
      backport:
        branches:
          - v1.9.2+RAI
        assignees:
          - "{{ author }}"
        label_conflicts: backport-conflicts
<<<<<<< HEAD
=======
  - name: backport patches to dev
    conditions:
      - base=master
      - label=backport-dev
    actions:
      backport:
        branches:
          - dev
        assignees:
          - "{{ author }}"
        label_conflicts: backport-conflicts
>>>>>>> 73e9c84 (Move to Rust 1.83 (#211))
