pull_request_rules:
  - name: backport patches to v1.8.2+RAI
    conditions:
      - base=master
      - label=backport-v1.8.2+RAI
    actions:
      backport:
        branches:
          - v1.8.2+RAI
        assignees:
          - "{{ author }}"
        label_conflicts: backport-conflicts
  - name: backport patches to v1.9.2+RAI
    conditions:
      - base=master
      - label=backport-v1.9.2+RAI
    actions:
      backport:
        branches:
          - v1.9.2+RAI
        assignees:
          - "{{ author }}"
        label_conflicts: backport-conflicts
